In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 12.4/12.4 MB 84.6 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

# 일반 리스트의 연산과 비교
print([[1, 2],[3, 4]] + [[5, 6],[7, 8]])
# print([[1, 2],[3, 4]] * [[5, 6],[7, 8]])



[[1, 2], [3, 4], [5, 6], [7, 8]]


In [7]:
a = np.array([[1, 2],
              [3, 4]])
print(a)
type(a)

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 

[[1 2]
 [3 4]]
[[ 6  8]
 [10 12]]


In [9]:
c = np.array([[5, 6],
              [7, 8]])
d = np.array([[1, 2],
              [3, 4]])
print(c - d)

e = np.array([[1, 2],
              [3, 4]])
print(e * 10)


[[4 4]
 [4 4]]
[[10 20]
 [30 40]]


# 행렬 곱(Matrix Multiplication) 
- 앞 행렬의 열의 수와 뒤 행렬의 행의 수가 같아야
- 결과 행은 앞 행렬의 (행의 수 x 뒤 행렬의 열의 수)를 가지는 행렬이 된다.
- 2행3열 @ 3행1열 --> "2행1열"의 결과 행렬이 반환 된다. 
- 여기서 중요한 건 행렬곱연산은 행렬의 사이즈를 줄일 수 있다는 것이다. 
- 데이터 과학에선 입력값의 특성(피처, 변수)이 너무 많을때 압축할때 행렬곱연산을 사용한다.  

In [10]:
# import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행3열

b = np.array([[10],
              [20],
              [30]])        # 3행1열

print(a @ b) # 결과는 2행1열
# [1×10 + 2×20 + 3×30]
# [4×10 + 5×20 + 6×30]

[[140]
 [320]]


In [11]:
# 전치행렬
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


# ​머신러닝에서 행렬곱 연산

​

머신러닝 알고리즘에서 행렬 W와 벡터 x를 곱하면 결과의 차원(원소 개수)이 줄어들 수도 있다.

예를 들어, 3차원 벡터를 2차원 벡터로 변환하는 경우이다.

In [12]:
# 2행 3열 행렬
W = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3차원 벡터
x = np.array([10, 20, 30]) # 3열
print("행렬곱 전 차원 : ", x.shape)

# 행렬 곱
y = W @ x

print(y) # 2열로 변경 됨 -> 차원축소
print("행렬곱 후 차원 : ", y.shape)

행렬곱 전 차원 :  (3,)
[140 320]
행렬곱 후 차원 :  (2,)
